export const gradientOptions: Record<string, { gradient: string; color: string }> = {
      whiteGradient: { gradient: 'linear-gradient(to bottom right, #ffffff, #f0f0f0)', color: '#333333' },
      blueGradient: { gradient: 'linear-gradient(to bottom right, #00c6ff, #0072ff)', color: '#ffffff' },
      pinkGradient: { gradient: 'linear-gradient(to bottom right, #ff7e5f, #feb47b)', color: '#ffffff' },
      greenGradient: { gradient: 'linear-gradient(to bottom right, #4caf50, #81c784)', color: '#ffffff' },
      purpleGradient: { gradient: 'linear-gradient(to bottom right, #a855f7, #6d28d9)', color: '#ffffff' },
      orangeGradient: { gradient: 'linear-gradient(to bottom right, #ff6a00, #ee0979)', color: '#ffffff' },
      tealGradient: { gradient: 'linear-gradient(to bottom right, #00b09b, #96c93d)', color: '#ffffff' },
      sunsetGradient: { gradient: 'linear-gradient(to bottom right, #ff5f6d, #ffc371)', color: '#ffffff' },
      coolBlueGradient: { gradient: 'linear-gradient(to bottom right, #2193b0, #6dd5ed)', color: '#ffffff' },
      warmCoralGradient: { gradient: 'linear-gradient(to bottom right, #f12711, #f5af19)', color: '#ffffff' },
      vibrantRedGradient: { gradient: 'linear-gradient(to bottom right, #ff512f, #dd2476)', color: '#ffffff' },
      goldenGradient: { gradient: 'linear-gradient(to bottom right, #f9d423, #ff4e50)', color: '#ffffff' },
      rainbowGradient: { gradient: 'linear-gradient(to right, #ff7e5f, #feb47b, #ff6a00, #ee0979)', color: '#ffffff' },
      radialGradient: { gradient: 'radial-gradient(circle, #ff9a9e 0%, #fad0c4 100%)', color: '#333333' },
      diagonalGradient: { gradient: 'linear-gradient(45deg, #ff6a00, #ee0979)', color: '#ffffff' },
      multiColorGradient: { gradient: 'linear-gradient(to right, #ff758c, #ff7eb3, #ff7eb3, #ff758c)', color: '#ffffff' },
      darkPurpleGradient: { gradient: 'linear-gradient(to bottom right, #4e54c8, #8f94fb)', color: '#ffffff' },
      softPastelGradient: { gradient: 'linear-gradient(to bottom right, #a8c8e0, #f2e6e6)', color: '#333333' },
      earthyGradient: { gradient: 'linear-gradient(to bottom right, #d3cce3, #e9e4f0)', color: '#333333' },
      nonLinearGradient1: { gradient: 'conic-gradient(#ff7e5f, #feb47b, #ff6a00, #ee0979)', color: '#ffffff' },
      nonLinearGradient2: { gradient: 'radial-gradient(circle at top left, #ff512f, #dd2476)', color: '#ffffff' },
      nonLinearGradient3: { gradient: 'linear-gradient(to top right, #00c6ff, #0072ff)', color: '#ffffff' },
      nonLinearGradient4: { gradient: 'linear-gradient(to bottom, #f12711, #f5af19)', color: '#ffffff' },
      nonLinearGradient5: { gradient: 'linear-gradient(to right, #4caf50, #81c784)', color: '#ffffff' },
    };